# Generated by Django 3.2.5 on 2023-09-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0002_alter_some_files_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
