# Generated by Django 3.2.5 on 2023-09-04 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwitter', '0004_dweet_dweet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweet',
            name='likes',
            field=models.ManyToManyField(related_name='dweet_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
